### PR TITLE
Adding Footer

### LINKED ISSUE #35: Add Footer to the website.
**Describe the solution you'd like**
Add a footer to the website consisting copywrites, etc.

### PR DESCRIPTION
**Pull request by sristy17**
## Description
Adding Footer

Fixes #35 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by knight1001d** [comment]
@sristy17 add the <Footer/> tag in ``src/app/layout.tsx`` file at the end of <body> tag and remove it from other files. This will keep the footer on every page since it will then be defined in the layout.

**Comment by knight1001d** [comment]
I have tested it on my machine and it is working

**Comment by sristy17** [comment]
> I have tested it on my machine and it is working
> 

Thanks will try for sure!

**Comment by sristy17** [comment]
> @sristy17 add the
> 
> tag in `src/app/layout.tsx` file at the end of tag and remove it from other files. This will keep the footer on every page since it will then be defined in the layout.

M still not getting! How to add this just a hint!

**Comment by knight1001d** [comment]
Just add footer.tsx in _components and add that footer in the layout file. Also, the footer will be visible after scrolling to the bottom only.
``src/app/layout.tsx`` should look like this:
```js
import "~/styles/globals.css";

import { Inter } from "next/font/google";

// import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "AutoMarket",
  description: "The Web Platform for Micro-automations",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

import Footer from "./_components/footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <>{children}</>
        <Footer/>
      </body>
    </html>
  );
}

```

**Comment by sristy17** [comment]
> Just add footer.tsx in _components and add that footer in the layout file. Also, the footer will be visible after scrolling to the bottom only. `src/app/layout.tsx` should look like this:
> 
> ```js
> import "~/styles/globals.css";
> 
> import { Inter } from "next/font/google";
> 
> // import { TRPCReactProvider } from "~/trpc/react";
> 
> const inter = Inter({
>   subsets: ["latin"],
>   variable: "--font-sans",
> });
> 
> export const metadata = {
>   title: "AutoMarket",
>   description: "The Web Platform for Micro-automations",
>   icons: [{ rel: "icon", url: "/favicon.ico" }],
> };
> 
> import Footer from "./_components/footer";
> 
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   return (
>     <html lang="en">
>       <body className={`font-sans ${inter.variable}`}>
>         <>{children}</>
>         <Footer/>
>       </body>
>     </html>
>   );
> }
> ```

Hey i need a help, if you dont mind can we connect on discord?

**Comment by prathamjagga** [comment]
sure, just ping on this username: pratham

> > Just add footer.tsx in _components and add that footer in the layout file. Also, the footer will be visible after scrolling to the bottom only. `src/app/layout.tsx` should look like this:
> > ```js
> > import "~/styles/globals.css";
> > 
> > import { Inter } from "next/font/google";
> > 
> > // import { TRPCReactProvider } from "~/trpc/react";
> > 
> > const inter = Inter({
> >   subsets: ["latin"],
> >   variable: "--font-sans",
> > });
> > 
> > export const metadata = {
> >   title: "AutoMarket",
> >   description: "The Web Platform for Micro-automations",
> >   icons: [{ rel: "icon", url: "/favicon.ico" }],
> > };
> > 
> > import Footer from "./_components/footer";
> > 
> > export default function RootLayout({
> >   children,
> > }: {
> >   children: React.ReactNode;
> > }) {
> >   return (
> >     <html lang="en">
> >       <body className={`font-sans ${inter.variable}`}>
> >         <>{children}</>
> >         <Footer/>
> >       </body>
> >     </html>
> >   );
> > }
> > ```
> 
> Hey i need a help, if you dont mind can we connect on discord?

**Pull request closed without merging**
