### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Meetjain1**
### Summary
This pull request enhances the project's README file by adding several important sections that improve the documentation and contribute to a better understanding of the project for new contributors and users. Additionally, it fixes various alignment issues to ensure the document is visually consistent and professional.

### Changes Made
1. **License Section**: Added a clear and concise license section with a link to the `LICENSE` file.
2. **Support Section**: Included a section detailing how users can get support and report issues.
3. **Code of Conduct**: Added a section outlining the project's code of conduct with a link to the `CODE_OF_CONDUCT.md` file.
4. **Ready to Contribute**: Introduced a section encouraging contributions with a link to the `CONTRIBUTING.md` file.
5. **Other Important Sections**: Added various other sections to enhance the comprehensiveness of the README.
6. **Links to Key Documents**:
   - `CONTRIBUTING.md`
   - `CODE_OF_CONDUCT.md`
   - `LICENSE`
7. **Alignment Fixes**: Corrected alignment issues throughout the document to ensure consistency and readability.

### Detailed Description
- **License Section**: This section provides clarity on the licensing of the project, ensuring users and contributors are aware of the terms under which the project is distributed.
- **Support Section**: The support section offers guidance on how to seek help, report bugs, and request features, improving user engagement and support processes.
- **Code of Conduct**: By adding a code of conduct section, we promote a respectful and inclusive community, with a direct link to the `CODE_OF_CONDUCT.md` file for detailed guidelines.
- **Ready to Contribute**: This section encourages contributions from the community, providing essential information and a direct link to the `CONTRIBUTING.md` file.
- **Various Other Sections**: These sections add further useful information, such as project overview, installation instructions, usage guidelines, and more, making the README a comprehensive guide.
- **Links to Key Documents**: Direct links to important documents make it easier for users and contributors to find and adhere to project guidelines.
- **Alignment Fixes**: Ensuring all sections are properly aligned enhances the visual appeal and readability of the README, contributing to a better user experience.

### Impact
These changes aim to:
- Improve documentation quality and usability.
- Foster a welcoming and organized community.
- Enhance user and contributor experience.
- Ensure all necessary information is easily accessible.

@prathamjagga have a look on this pr . Thanks , I am working under gssoc

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* Toolchain:
* Other:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

## Screenshots (if applicable)

If applicable, add screenshots to help explain your changes.

## Additional Information

Any additional info that might be helpful in reviewing pull request.

### CODE REVIEW

**Comment by Meetjain1** [comment]
@prathamjagga have a look on this PR. Thanks

**Comment by Meetjain1** [comment]
> @prathamjagga have a look on this PR. Thanks

please review this pr . Thanks

**Comment by Meetjain1** [comment]
> > @prathamjagga have a look on this PR. Thanks
> 
> please review this pr . Thanks

@prathamjagga

**Comment by Meetjain1** [comment]
> > > @prathamjagga have a look on this PR. Thanks
> > 
> > 
> > please review this pr . Thanks
> 
> @prathamjagga

@prathamjagga Please review this Pr. Thanks

**Comment by Meetjain1** [comment]
> > > > @prathamjagga have a look on this PR. Thanks
> > > 
> > > 
> > > please review this pr . Thanks
> > 
> > 
> > @prathamjagga
> 
> @prathamjagga Please review this Pr. Thanks

@prathamjagga

**Comment by Meetjain1** [comment]
@prathamjagga

**Comment by Meetjain1** [comment]
@prathamjagga please review this pr . Thanks

**Comment by prathamjagga** [comment]
@Meetjain1 We don't wanna change the README right now.

**Pull request closed without merging**
